# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - diabetespredictionapp01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bitscontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_82fa8f04769b4a20bd78d95f359cc030 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b3874c67d62b41d39d89092b93db955a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bitscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_82fa8f04769b4a20bd78d95f359cc030 }}/diabetes_prediction_app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'diabetespredictionapp01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_052c96859c5f49da866ecb3964131fb3 }}
        images: 'bitscontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_82fa8f04769b4a20bd78d95f359cc030 }}/diabetes_prediction_app:${{ github.sha }}'